---
title: 文學教育
author: deadfate
date: '2020-01-20'
slug: chinese literature
categories:
  - 想法
tags: 
  - 隨筆
  - 文學
---
這篇本來是跟某個朋友討論各校中文系，後來插入文學教育現況。為了維持文章的完整性，就只保留文學教育與改革的部分。  

## 文學教育與改革
以前的「文學課程」(雖然不限定語言，不過英文其實沒談什麼文學跟分析，基本上停留在語法，就先不討論)，是直接跟你講結論。例如給你看一篇陶淵明的文章，看完直接跟你說他是田園派，然後田園派的文字風格就是文章那樣，請背起來。這樣聽完當然會滿頭問號，推論過程呢？？？？為什麼他是？你怎麼從文章看出來的？文章的哪些特徵哪些理由哪些證據，支持「陶淵明是田園派」這個結論？還是理由就是「感覺起來是」，完全沒有說明的空間？這種方式超級怪的，明明是知識，又不是什麼「騎機車」這種身體技能，卻只能用「你自己感覺辣」這種方式學會。

我並不是指「感受」對文學不重要，「感受」是文學的基礎，那些文人就是要瞎78多愁善感，才有辦法寫出這五千多年的文學史。問題是，我們要有能力分析「哪些部分、哪些技巧」讓我們有這樣的感受，我們才有能力模仿、學習，並用類似的模式，創造出讓別人會有相同感受的作品吧？

而且，上面「這篇文章看出他是田園派，然後田園派的文字風格就是文章那樣」，這樣的推論方式，非常明顯是一種「套套邏輯」，就是拿自己解釋自己，我現在才驚覺，哇草，整個國高中國文，都是這樣子非常有邏輯謬誤的說明方式。我會說這樣的說明是套套邏輯，因為他呈現這樣的模式：先用A解釋B，那什麼是A？再用B解釋A。「這篇文章的文字風格，看出他是田園派。那田園派的文字風格是如何？就是這篇文章這樣。那這篇文章的文字風格……？就是田園派。那田園派的文字………」，就一直這樣無限循環下去，最後我還是不知道，是他文章的哪些細節，是「哪幾句話」，可以讓我們把他詮釋、說明成田園派。

國文改革的方向，就是讓學生有能力有工具，有一套思考流程，可以回答出「如何從這篇文章看出他是田園派」這種問題，可以從文章內容，推論出學界公認的共識。我記得 [某段演講](https://youtu.be/t6GKtMNyFAI)，朱宥勳有提出一個很簡單的方式，可以讓人很快的練習「文學分析」是如何。  

這個方式就是問三個問題，看完一篇文章之後，問：「我有什麼感覺？」、「為什麼？」、「在哪裡？」。所以，如果套到陶淵明的文章身上，「看完有什麼感覺？」，有田園感；「為什麼？」，可能是使用的文字，敘事方式，或文字描述的內容(風景)；「在哪裡？」，上述那些理由的證據在文章的哪裡？把細節提出來。用這樣的方式，我們才有能力分析「我的感受從何而來」，也才能離開「背結論」的階段，進到有能力「獨立面對新文章」的階段。

我覺得這樣的能力真的很重要，因為文學「不只是文學」，生活中舉凡小說、電影、戲劇，甚至廣告，都有跟文學類似之處，都能觸發我們不同的感受，甚至「灌入」一些東西到我們腦海裡，而學習如何分析文學的基本能力，是成本最低的，因為只要會看字就好(這論點也是來自上面那段影片)。有了這個能力，我們才有辦法分析自己的感受從何而來，然後再試著學五千年來文人都在用的模式，把感受用同樣的方式表達出來。  

這才是文學教育改革的關鍵。  

2020/1/20補充：  
這篇文章的很多想法，都來自朱宥勳的書跟演講，我就不全部列出了，只取一本滿精華的書推薦：[只要出問題，小說都能搞定](https://www.books.com.tw/products/0010747442)  

最後更新```r Sys.Date()```