---
title: 社會科學學徒需要的基本能力
author: 黃天原
date: '2020-01-20'
slug: the basic skills required for a social science apprentice
categories:
  - 想法
tags:
  - 隨筆
---
關於前一篇文提到，即使在自己想要的科系，有些這個科系需要的基本能力，我還是得自己找資料、看文章，在其他地方學怎麼樣「**把自己的論點講清楚**」。這在我大學剛入學困擾我非常久，畢竟社會科學大學生，一定會接觸很多社會科學的概念。而概念通常很難，光是理解就已經耗掉很多時間了，所以課程上應該就不太會再去教學生，如何把自己的論點或看法，清楚的表達出來。  

這會導致一個問題，就是我沒有很好的一套「**方法**」可以操作我的語言或文字，把我想講的東西清楚而完整的表達出來。而這些東西基本上在基礎教育階段也不會有人教你......最後就變成我不知道如何表達我理解的東西，更甚者，我不知道如何去「**批評**」其他人的文章，因為我沒辦法拆解他文章的邏輯組成，或是他的思考組成。這個問題，一直到我看到朱家安的文章，才開始思考怎麼解決。朱家安的文章，通常會講清楚他要討論什麼，文章中用到的概念，其「**定義**」是什麼。[像這篇文章](https://opinion.udn.com/opinion/story/6068/1260232)，他就很清楚的示範，怎麼用理由思考，然後組織自己的論點。或是像陳瑞麟的[邏輯與思考](https://www.books.com.tw/products/0010471280)，或是[朱家安自己出的書作文超進化](https://www.books.com.tw/products/0010813963)，都有助於解決我的疑惑。  

總之，還好有接觸到這些資源，不然不知道要怎麼寫下自己的想法了。<br>
更麻煩的是，對於沒有這類訓練的普通人，其實很難「順利的」完成社會系所開設出來的課堂作業。一個好的學習，通常自己有能力去評價自己完成的成果，找到優點與缺點，進而改進缺點，保留優點。例如發現泡茶很失敗不好喝，然後上網搜尋發現泡茶一定需要 1. 先溫壺 2. 第一泡泡散茶葉然後另外裝不要喝。有這兩個步驟，泡出來的茶才會好喝。這就找到問題並改進的學習。但如果沒辦法發現一個論證是由「論點 + 理由/事實」所構成，就根本沒辦法去評價自己在作業中的論證。可能老師會給你回饋，但自己也很難看懂。（2023/10 補充）  

2020/01/20 補充：  
說到底就是找不出別人的論點跟理由是什麼，當然也無法評價別人「理由→論點」這樣的一套邏輯推論合不合理。順便再推一本朱家安推薦的書[論文教室：從課堂報告到畢業論文](https://www.books.com.tw/products/0010819459?sloc=main_mb)。同樣也可以學到上述的事情。  
