---
title: 作文超進化 筆記心得
author: deadfate
date: '2020-02-20'
slug: how to write well
categories:
  - 想法
tags:
  - 文學
  - 認真
  - 乾貨
---
[這本書](https://www.books.com.tw/products/0010813963)真的很不錯。教了一些基本的寫作技術，例如動詞該怎麼用、細節該怎麼寫，才能吸引觀眾眼球，或是動態的感覺該如何營造，靜態的情緒要如何描寫。這些林林總總的技術，通通都包含在這本書裡。  

還有所謂的「修辭」。以往在學那些修辭技巧根本都是用背的，完全不知道什麼擬人、轉化、排比這些修辭有三小作用。這本書裡面給你解釋的清清楚楚。  

我主要是想摘要這本書的一到四章，以及後半部分，也就是朱宥勳寫的「情意篇」。這部分如上所述，提供了相當多的「寫作技術」，如果跟他的另一本書 [只要出問題，小說都能搞定](https://www.books.com.tw/products/0010747442)搭配起來，估計就掌握一般的故事型態跟文學技術。摘要一下，也方便我日後快速查閱。

那就開始吧。  

## 一、作者的任務  
就是先設立文章的對象、目標。訂好之後，一篇文章最基本要符合三個原則，就是完整、具體跟有趣。「完整」就是把所有資訊提供清楚，不要預設別人會已經知道哪些資訊，所以不用再提；「具體」則是需要提供例子、證據或詳細說明；最後「有趣」，就是要找出文章主題中能夠吸引人的地方，盡量找出會讓讀者出乎意料、有興趣了解的點，並以此為重心，強力猛攻。  

這三個點就是文章最基本的原則。

## 二、設定目標：給讀者一道光  
就是寫作時請設立好「一個目標」，並努力地朝這個目標前進就好。這在 [第二十二章](#二十二章、結尾：抓住漫不經心的讀者)會再提及。  

## 三、畫大綱：小口小口吃，比較容易  
草擬一份大綱。再設立好目標後，就先把文章的總目標切成幾個話題，作為中間的段落，話題可以再分成小話題。如果擬不出大綱，想不出足夠的話題，可能代表跟這個「目標」不夠熟，正好可以換個目標再試試。  

大綱擬好後，就只要照著大綱，把開頭、各段話題跟結尾逐步填滿，可以完成一篇還不錯的文章了。  

## 四、文字基本功：好好呼吸  
這章重點就兩個，適當斷句跟善用引號。


## 二十一、開頭：先拋餌，再解釋  
這章主要討論「如何開頭」這回事。他先提了

他提出了一個「先拋餌，再解釋」的方式，簡單來說，就是先丟出一個吸引眼球的東西，後續再慢慢補上解釋，這樣觀眾就會好奇「為什麼是這樣？」，進而願意讀下去。那該拋什麼餌呢？她先說明了一般敘事文章架構的兩個部分，「事件」跟「情感」。用他的例子來說，「失戀的感覺」是情感，而「失戀的過程」則是一個事件。這兩個東西混在一起，就會是一般人討論「失戀」的所有內容，一堆情感加事件混再在一起哇啦哇啦地全盤托出。

要拋餌，就是先拋一個事件，或是一種情感，後續再用另一個部分解釋，讀者會願意繼續看下去，以解開心中的好奇。  

摁...用事件開頭，應該就像是「喀啦喀啦，喀啦喀啦...我反覆敲打著鍵盤，瘋狂的按壓ctrl+enter兩個按鍵，然後右手托起下巴，左手拿起啤酒，重重地喝了一大口。」

那用情感開場呢？練習看看好了...  
「半夜三點，我煩躁的坐在椅子上，長吁短嘆，唉聲嘆氣。不禁懊惱回想，自己為何淪落成這副德性？...」  

好吧，雖然說是情感開場，但真的很容易就想加上一大堆動作。事件開場感覺比較好上手。  

## 二十二、結尾：抓住漫不經心的讀者
這章沒什麼太複雜的。結尾的方式很簡單，就是把文章最初的設定的目標，再堅定的強調一次，不要沾染上以往考試作文的習慣，來個開放式結尾。  

更好的方式，可以開頭提一次目標，中間的段落提一次，最後的結尾再提一次。如此一來，讀者對這篇文章說了什麼，就會有深刻的印象。  

## 二十三、細節：「物件」與「動作」的連連看  
這章說明如何創造或觀察出大量細節。作法就是物件與動作的連連看，寫出那個場景的物件，物件發生了什麼動作，再連到下一個相關物件，發生了什麼動作，如此「物件、動作、物件、動作……」不斷重複下去，就有大量的細節讓人挑選了。  

作者舉了簡單的例子，例如以電風扇為初始物件，電風扇轉動就是動作，吹出來的風撥動了窗簾，窗簾就是下一個物件，依序下去觀察...。用這個方法，最後確實能寫出大量的細節。  

有能力描寫大量的細節後，剩下的工作就是精煉，篩選出符合自己需要的細節就好。  

## 二十四、詳與略：重點處放大  
如果要避免「流水帳」，那麼內容就必須有詳細與簡略。通常並不會每個話題都塞滿滿，只要選出自己最想講的重點詳細寫，其他部分簡略提及，透過其他簡短的段落，襯托出詳細且重要的一段，讀者的目標就會被最詳細的那段吸引。  

也因此，通常創作者會喜歡在倒數第二個段落詳細地寫，最後一段再下一個乾淨俐落的結論，透過「詳—略」的轉換，讓讀者注意力自動集中在最後一段的結論上，更能強調整篇文章的目標（達到二十二章的結尾方式的目的）。  

## 二十五、動與靜：一波帶走讀者的視線  
前面的部分，主要關於文章的架構。這章開始會更詳細討論，該如何使用文字，達到想要的效果。就是所謂「優化文字」。  

第一種方法，就是增加文章的動詞。人天生感官就容易受到「動作」吸引，因此增加文章中的動作，就是最好吸引注意的方法，如此文章也會更流暢、更易於閱讀。這也是為什麼會有「擬人」這個修辭，目的就是讓不會動的東西，也能產生動作。作者舉的例子：「大樹伸出枝枒，碰到教室上面的屋頂」，這樣就比「大樹長得很高」還要吸引人。如果再加上二十三章提到的細節寫法，就能讓物件不斷地動來動去。  

至於形容詞跟副詞，他們並不是沒有出場空間。但是越多複雜的美詞佳句或成語，就會讓讀者需要更「靜」下心品嘗，才有辦法細細體會。因此，應該讓整篇文章的主要內容，都是動詞，形容詞與副詞在特別的地方，才能起到點睛的效果。  

## 二十六、節奏：用文字遙控讀者的情緒  

| 節奏加快 | 節奏變慢 |
|-------- |---------|
| 用字簡單 | 用字困難 |
| 句子短   | 句子長|
| 段落長   | 段落短|
| 動詞多   | 形容詞、副詞多|
| 事件多、細節少 |事件少、細節多|
| 內容具體 | 內容抽象|  

這表格講的非常清楚。所以節奏要視情緒而定，如果是悲傷的情緒，就應該放慢節奏，這時候就輪到形容詞出場。如果是快樂的情緒，或是打鬥場景，就應該加快節奏，進而影響讀者的心情。  

## 二十七、組合與染色：換位置，換掉讀者的腦袋  
形容詞怎麼用的好？  

第一種方法，改變一般的形容詞組合。把形容詞放到平常不會放的地方，例如「眼神很飄逸」。  

第二種方法叫「染色」。要形容一個人或東西，不要直接把他套滿形容詞，可以試著把旁邊的東西「染色」，染上想描寫的情緒，要被形容的人自然就有了情緒。  

## 二十八、腔調：假裝自己在說人話  

找出自己喜歡的詞彙跟句型，久了，就可以培養出自己的「腔調」跟特色。

## 二十九、修辭四大原理：重複  
後面的部分，討論各式修辭背後的原理。掌握原理，才能合理的使用「修辭」這種工具。  

兩種重複。一是重複的內容，不斷地在不同的段落提及，可以加深讀者印象，包括結尾再重複一次文章目標，影視應用這種修辭原理。  

另一種重複，則是不斷的重複相同的句型或格式，甚至押韻也是這種重複。而重複不需要像排比對仗如此工整，只要讓讀者感受到重複的東西出現就行。

## 三十、修辭四大原理：對比  
有兩個主要原則。  

物以稀為貴，想突顯的東西，要與其他東西相對；壓軸法則，陪襯的放前面，重要的放最後。

所以重複跟對比可以組合成combo：重複幾次一樣的東西(句型結構、內容)，但最後一次用不同或相反的東西，突顯想表示的點。這個方式在二十四章的「詳與略」、二十五章的「動與靜」也都有很不錯的實作。本質上，都是透過對比，製造出記憶點。  

## 三十一、修辭四大原理：聯想

拿B寫A，B跟A之間要有共同點。而且還會附贈B的氣質。其實就是譬喻會改變我們對A的想法，這在 [這篇文章](https://www.mplus.com.tw/article/2131)跟 [這本書](https://www.books.com.tw/products/0010328131)有詳細說明。而二十七章的組合與染色，也是使用到這個原理。當我們拿金錢比喻時間，拿玫瑰比喻愛情，時間就會染上金錢的特質，愛情也會染上玫瑰的特性。

## 三十二、修辭四大原理：典故
就是埋彩蛋，要讓預設讀者看得出來。而典故只是附件，不懂也不影響閱讀，懂了能讓讀者產生樂趣。  

例如孔乙己、雅量著名文章，其經典格式在ptt或其他留言區就會被大量改編使用。而ACG中的「捏他」或致敬也有同樣的效果。  

## 最後  

回應文章開頭，這本書教授的寫作技術相當實用。相較於那些不知何時會用到的美詞佳句、古人名言，這本書的這些技術，是扎扎實實的基本功。或是我們用潮一點的AI行話，這是「文學落地」必讀的書籍、必備的技能。