---
title: 《超速學習》筆記
author: 黃天原
date: '2020-08-09'
slug: Ultralearning-note
categories:
  - 想法
tags:
---

## intro 
超速學習：<https://readmoo.com/book/210139192000101>  


其實這本書跟 [之前的文章](https://deadfate.rbind.io/2020/08/01/how-to-learning-and-how-to-write/)提到的學習法的書是一起買的，不過前兩本我比較偏重「如何透過輸出，強化自己對概念的運用」，這本就真的是拿來看學習法的部份了。

順便提醒自己一下，看學習法相關書籍的時候，要帶著自己的目的跟問題去看。例如，如果我在工作專心上有問題的話，就帶著這個問，看書中怎麼剖析問題的原因，解決方法是什麼，「為什麼這麼做？為什麼這樣可以解決？」  

最後一個問題最重要，因為只有了解它方法的運作原理，或是能夠有效果的原因，這樣才能靈活運用，讓方法變成「適合自己的方法」。像我自己很久以前看成甲的《精準學習》，一來是他提供的學習方法很雜，二來是它並沒有把「為什麼這麼做」的理由講清楚，變成有點像是路邊醫美廣告—「藥品＋成功案例」，我只看到作法跟成功案例，但這沒辦法說服我照著做就會成功。  

相較之下，這本除了提供案例，在原因或原理上也有所著墨，比較能夠說服我。  


## 筆記部份  

### ch1 先畫地圖

### ch2 專心  
ch2是跟專心有關，討論人要如何進入到專心工作的狀態。  

當我碰到我喜歡、我有興趣的任務時，比如看有興趣的書、學一個有興趣的套件，我進入到工作狀態的門檻比較低，而且可以輕易地就全心全力投入。但問題在於，只要我面對到工作或類工作的事項，不管內容是怎樣，我就會突然變得很沒動力，不然就是被自己畫的餅噎死。

要如讓自己「願意面對」工作，就算五分種也好，而且可以小目標小目標的產出或完成進度，以解決拒絕專心的毛病，是我得處理的問題。  

目前設立目標，逐步執行的部份，是透過看 [子彈筆記](http://moo.im/a/fqyLRV) 的方式學習，心得我也放在 [另一篇心得文](https://deadfate.rbind.io/2021/03/22/goal-management/) 中。

### ch3 不能實際使用的知識對我來說沒有用  
ch3是在講學習應該要直接從「想達成的目標」反過來建立學習歷程，並提及了一個概念，叫做「學習遷移」。遷移學習是在討論，我們習得的知識，要如何應用在實際的場合。而要達到「學習遷移」最直接的方式，就是「直接學習」，就是直接從你想應用的環境，學習該項技能。  

例如，如果想當遊戲設計師，而你會需要程式設計的能力，那就直接從「製作遊戲」學習所需要程式語言能力。或是說我想學如何爬蟲，那就不要考慮我還缺什麼缺什麼，直接試著執行一遍就對了，試了就知道要學會這個東西，還缺哪些部分。  

### ch4 挑弱點練習
ch4就是在講要怎麼針對學習時的弱點練習。 

在直接從「實際情況」進行學習之後，下一步就是要找出自己的「學習這項能力」時，有哪些環節是不夠熟練的、需要被「特訓」的。就我學習資料分析至今的經驗為例，我認為自己最不擅長的部份就是議題設定，或問題挖掘。一份好的分析，在最初的議題設定非常重要，它會決定「要蒐集哪些資料」、「用什麼分析方法」等分析方向。或者是說，要對人間（?）世界有非常多的觀察，才會有想要用資料去回答的疑問吧。總覺得我很多時候是空有一身功夫，但找不到施力點。  

如果要訓練議題設定的能力，感覺還是要多看某個主題的相關文章。之後再把《[論文教室](https://www.books.com.tw/products/0010819459)》的相關章節研究一下。無論如何，廣泛的閱讀，並且在閱讀過程中，有意識的提問跟紀錄，總是會讓自己找到有趣的題目。  

### rule 5 提取記憶

這個規則的本體是「事後回想」或是「測驗」。這其實也算是老生常談，我在很多學習法的書也有看過相關討論，簡單來說，就是在學習後用不開書回想的方式，回憶自己理解或記住了哪些部分，會比重複看學習素材更有效果。就跟以前唸書唸完一章之後，直接做習題跟測驗卷，而且不能翻書或看解答。當然，技術技能不是靠記憶就能學會，這種就必須自己設計一些小練習，或是要完成的小目標小作品等等。  

如果是社科比較常見的概念、論說文類型的知識，可以把作者的主要論點，或是文本的各個章節轉換成一個主要問題（有點像各大社會學系所很愛講的「問題意識」），而回答問題代
的答案，就會是你想理解或記憶的重要論證跟理論。

事前就預先看過測驗問題，在學習的時候會更有效率，因為腦袋會自動搜尋自己需要用來解決問題的知識。

其實這章應該要跟 rule 6 的評價學習成效一起看